"""
Convert the 20260713 "all layer label" COCO dataset into a single-class YOLO
segmentation dataset, preserving the existing Roboflow train/valid split.

Every discrete membrane layer (including the new "inner" class) is collapsed
into one "EV" class per polygon. Multilayer status is determined later via
polygon containment, not by a dedicated class here.

Class remapping (Roboflow "CryoAI 20260611" export, categories found in
train/valid _annotations.coco.json):
  items-nfaR (cat 0)   -> unused root placeholder, 0 instances, dropped
  EV (cat 1)           -> class 0 "EV"
  Incomplete (cat 2)   -> class 0 "EV"
  Low conf EV (cat 3)  -> class 0 "EV"
  MV (cat 4)           -> class 0 "EV"
  inner (cat 5)        -> class 0 "EV"
  non-EV (cat 6)       -> dropped (contamination, not a vesicle layer)
"""

import argparse
import json
from pathlib import Path
from collections import defaultdict

# Mapped by category NAME, not numeric COCO id -- ids aren't guaranteed
# stable across Roboflow export versions, names are.
CATEGORY_NAME_TO_CLASS = {
    "EV": 0,
    "Incomplete": 0,
    "Low conf EV": 0,
    "MV": 0,
    "inner": 0,
    "Overlapping": 0,   # real vesicle-layer polygon flagged as overlapping another; not contamination
    "non-EV": None,     # dropped (contamination, not a vesicle layer)
    "items-nfaR": None,  # unused root placeholder
}
CLASS_NAMES = ["EV"]

ROOT = Path(__file__).parent.parent.parent / "CryoAI"
DEFAULT_SOURCE_NAME = "roboflow - 20260713 all layer label"
DEFAULT_OUTPUT_NAME = "roboflow_20260713_all_layer_singleclass"


def convert_split(coco_path: Path, images_src_dir: Path, img_out_dir: Path, label_out_dir: Path) -> dict:
    img_out_dir.mkdir(parents=True, exist_ok=True)
    label_out_dir.mkdir(parents=True, exist_ok=True)

    with open(coco_path, "r", encoding="utf-8") as f:
        coco = json.load(f)

    cat_id_to_name = {cat["id"]: cat["name"] for cat in coco["categories"]}

    anns_by_image = defaultdict(list)
    for ann in coco["annotations"]:
        anns_by_image[ann["image_id"]].append(ann)

    stats = {"n_images": 0, "n_labels": 0, "n_instances": 0, "n_dropped": 0, "images_without_labels": []}
    movement = defaultdict(lambda: defaultdict(int))

    for img in coco["images"]:
        src_path = images_src_dir / img["file_name"]
        if not src_path.exists():
            print(f"  [WARN] image not found: {src_path}")
            continue

        img_w, img_h = img["width"], img["height"]
        anns = anns_by_image.get(img["id"], [])

        label_lines = []
        for ann in anns:
            orig_name = cat_id_to_name.get(ann["category_id"], f"cat_{ann['category_id']}")
            if orig_name not in CATEGORY_NAME_TO_CLASS:
                raise ValueError(
                    f"Unmapped category {orig_name!r} (id {ann['category_id']}) in {coco_path} -- "
                    f"add it to CATEGORY_NAME_TO_CLASS before converting."
                )
            new_cat = CATEGORY_NAME_TO_CLASS[orig_name]

            if new_cat is None:
                movement[orig_name]["DROPPED"] += 1
                stats["n_dropped"] += 1
                continue

            seg = ann.get("segmentation")
            if not seg:
                continue
            polygon = seg[0] if isinstance(seg[0], list) else seg

            coords = []
            for i in range(0, len(polygon), 2):
                x = max(0.0, min(1.0, float(polygon[i]) / img_w))
                y = max(0.0, min(1.0, float(polygon[i + 1]) / img_h))
                coords.extend([f"{x:.6f}", f"{y:.6f}"])

            if len(coords) >= 6:
                label_lines.append(f"{new_cat} " + " ".join(coords))
                movement[orig_name][CLASS_NAMES[new_cat]] += 1
                stats["n_instances"] += 1

        # Copy image
        dst_path = img_out_dir / img["file_name"]
        dst_path.write_bytes(src_path.read_bytes())
        stats["n_images"] += 1

        if label_lines:
            label_path = label_out_dir / f"{Path(img['file_name']).stem}.txt"
            label_path.write_text("\n".join(label_lines) + "\n", encoding="utf-8")
            stats["n_labels"] += 1
        else:
            stats["images_without_labels"].append(img["file_name"])

    stats["movement"] = dict(movement)
    return stats


def write_dataset_yaml(output_root: Path, has_test: bool):
    yaml_path = output_root / "dataset.yaml"
    lines = [
        f'# YOLO dataset config for {output_root.name} - 1 class',
        '# Generated by prepare_all_layer_singleclass.py; all membrane-layer classes',
        '# (EV/Incomplete/Low conf EV/MV/inner) collapsed into "EV"; non-EV dropped.',
        '# Existing Roboflow train/valid(/test) split preserved as-is (no re-split).',
        f"path: {output_root.as_posix()}",
        "train: images/train",
        "val: images/val",
    ]
    if has_test:
        lines.append("test: images/test")
    lines += [
        "",
        f"nc: {len(CLASS_NAMES)}",
        "names:",
    ] + [f"  {i}: {name}" for i, name in enumerate(CLASS_NAMES)]
    yaml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] Wrote {yaml_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-name", default=DEFAULT_SOURCE_NAME,
                         help="Folder name under 'training images/' holding the raw Roboflow COCO export")
    parser.add_argument("--output-name", default=DEFAULT_OUTPUT_NAME,
                         help="Folder name to create under 'training outputs/' for the converted YOLO dataset")
    args = parser.parse_args()

    source_root = ROOT / "training images" / args.source_name
    output_root = ROOT / "training outputs" / args.output_name

    # Roboflow split name -> YOLO split name. "test" is included automatically
    # if the export has one (the 20260713 export didn't; newer ones may).
    splits = {"train": "train", "valid": "val"}
    if (source_root / "test" / "_annotations.coco.json").exists():
        splits["test"] = "test"

    print(f"Source:  {source_root}")
    print(f"Output:  {output_root}\n")

    all_stats = {}
    for src_split, dst_split in splits.items():
        coco_path = source_root / src_split / "_annotations.coco.json"
        images_src_dir = source_root / src_split
        img_out_dir = output_root / "images" / dst_split
        label_out_dir = output_root / "labels" / dst_split

        print(f"=== {src_split} -> {dst_split} ===")
        stats = convert_split(coco_path, images_src_dir, img_out_dir, label_out_dir)
        all_stats[dst_split] = stats

        print(f"  images: {stats['n_images']}, labeled: {stats['n_labels']}, "
              f"instances: {stats['n_instances']}, dropped(non-EV etc.): {stats['n_dropped']}")
        if stats["images_without_labels"]:
            print(f"  [WARN] {len(stats['images_without_labels'])} image(s) with no surviving labels: "
                  f"{stats['images_without_labels']}")
        for orig_name, dests in sorted(stats["movement"].items()):
            for dest, count in sorted(dests.items()):
                print(f"    {orig_name:>15s}: {count} -> {dest}")
        print()

    write_dataset_yaml(output_root, has_test="test" in splits)

    total_instances = sum(s["n_instances"] for s in all_stats.values())
    total_images = sum(s["n_images"] for s in all_stats.values())
    print(f"[OK] Dataset ready at: {output_root}")
    print(f"[OK] Total: {total_images} images, {total_instances} instances")
    for split_name, stats in all_stats.items():
        print(f"  {split_name}: {stats['n_images']} images, {stats['n_instances']} instances")


if __name__ == "__main__":
    main()
